---
abstract: 'Layout a log message as a JSON hash, including MDC data'
author:
  - 'Michael Schout <mschout@cpan.org>'
build_requires:
  Encode: '0'
  File::Spec: '0'
  IO::Handle: '0'
  IPC::Open3: '0'
  Log::Log4perl::MDC: '0'
  Test::More: '0'
  Test::Most: '0'
  Test::Warnings: '0'
  perl: '5.010'
  utf8: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
  perl: '5.010'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.024, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Log-Log4perl-Layout-JSON
provides:
  Log::Log4perl::Layout::JSON:
    file: lib/Log/Log4perl/Layout/JSON.pm
    version: '0.59'
requires:
  Carp: '0'
  Class::Tiny: '0'
  JSON::MaybeXS: '0'
  Log::Log4perl: '0'
  Log::Log4perl::Layout: '0'
  Log::Log4perl::Layout::PatternLayout: '0'
  Log::Log4perl::Level: '0'
  Scalar::Util: '0'
  parent: '0'
  perl: '5.010'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/mschout/Log-Log4perl-Layout-JSON/issues
  homepage: https://github.com/mschout/Log-Log4perl-Layout-JSON
  repository: https://github.com/mschout/Log-Log4perl-Layout-JSON.git
version: '0.59'
x_generated_by_perl: v5.30.3
x_serialization_backend: 'YAML::Tiny version 1.73'
x_spdx_expression: 'Artistic-1.0-Perl OR GPL-1.0-or-later'
